Production Version 1.0
shuja-shah/crypto-xe pull request #1
Opened 2022-10-06 21:38 UTC by shuja-shah

## Introduction 

- **This web application tracks Crypto Currency** 
-  **The data is updated every 5 minutes**
- **API USED "COINRANKING"** [link](https://coinranking1.p.rapidapi.com/coins)
-  [Live Demo Here](https://cryptoxe.netlify.app)
- [Presentation Video](https://youtu.be/FU9CmCAUTH0)

## Home Page

- **Home page shows all the coins with their image and sorts them in different categories i.e. ("Most Popular Coins, Top Ten Coins ...etc")**

## Details Page

- **When a Particular Coin is Clicked, A new window opens showing all the data about that particular coin.**
-  **Used Router to Achieve Lazy Loading and render the component**
-  **Used Redux and the Global State to get the data about that particular coin ```useSelector()```.**

## Responsiveness 

- **Application is created using the "Mobile First Approach" and is scaleable to tablets and Desktops.**

## Performance

- **Used Router's Lazy Loading to load components** 
-  **Used React Persist to eliminate Latency of the API**

*Cheers guys 🥂 Happy Coding 👏🏻 👏🏻*

2022-10-06 22:28 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️

Hi @shuja-shah,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ You used Gitflow correctly
✅ Linter checks passed
✅ Good descriptive PR 👍 
✅ Nice project presentation and the hosted app works fine as expected 👍  

## Required Changes ♻️
_Check the comments under the review._

You did well so far on your project but you skipped one more important feature that is very necessary to have on your app.

- [ ] Kindly add a search bar so one can enter the name of the crypto that they want to have details about. When a user searches and then sees that search and clicks on it to see more details of it. 👍 
- I marked green on the ones you did from the requirement and red on the missing part from the screenshot below.
![image](https://user-images.githubusercontent.com/50941074/194427431-e8d4c1e8-cefa-4ea2-afea-e5f0e970998c.png)

**I suggest you have the search either on the top bar, or add it below the texts you have on the hero section of the homepage**


Something around this screenshot below
![image](https://user-images.githubusercontent.com/50941074/194427851-651b13e3-6ea4-4464-b679-93ed02bcaefc.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-10-06 22:28 UTC, AmaduKamara commented on README.md
> +- The Awesome Code Reviewers :heart:
- [ ] Kindly add to your acknowledgment below, by giving credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/). They deserve credit as well because their design is used as inspiration for your work. Please add that 👍

2022-10-06 22:28 UTC, AmaduKamara commented on src/Redux/configureStore.js
> +}, applyMiddleware);
- [ ] When I run the tests, this section produces an error. Kindly work on it

![image](https://user-images.githubusercontent.com/50941074/194429940-350617c5-ffc7-4a44-975a-f936c47ece9e.png)

2022-10-07 11:16 UTC, shuja-shah commented
## Hello, I've Implemented the requested Changes.

2022-10-07 11:30 UTC, brytebee approved these changes
Hi, @shuja-shah👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great UI design.✔️
- The README looks professional.✔️
- All tests run and are green.✔️


##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/fxsqOYnIMEefC/giphy.gif)

Good luck! 🎉 

##

###  **Optional Suggestions:**
- N/A

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-07 11:49 UTC, merged